export const SET_TOKEN = "SET_TOKEN";
export const LOADING_TOKEN = "LOADING_TOKEN";
export const ERROR_TOKEN = "ERROR_TOKEN";

export const GET_BOOKINGS = "GET_BOOKINGS";
export const SET_BOOKINGS = "SET_BOOKINGS";
export const LOADING_BOOKINGS = "LOADING_BOOKINGS";
export const ERROR_BOOKINGS = "ERROR_BOOKINGS";
export const APPLY_FILTERS = "APPLY_FILTERS";
export const SET_FILTER_BY_ID = "SET_FILTER_BY_ID";
export const SET_FILTER_ID_GREATER_EQUAL_THAN =
  "SET_FILTER_ID_GREATER_EQUAL_THAN";
export const SET_FILTER_ID_LESS_EQUAL_THAN = "SET_FILTER_ID_LESS_EQUAL_THAN";
export const SET_FILTER_BY_PRICE = "SET_FILTER_BY_PRICE";
export const SET_FILTER_PRICE_GREATER_EQUAL_THAN =
  "SET_FILTER_PRICE_GREATER_EQUAL_THAN";
export const SET_FILTER_PRICE_LESS_EQUAL_THAN =
  "SET_FILTER_PRICE_LESS_EQUAL_THAN";
